### ISSUE TITLE
dockerfile文件目录放置错误

### ISSUE THREAD

**Issue by muniao** [javastacks/spring-boot-best-practice#1]
Dockerfile文件的放置位置应该是pom.xml文件一致才能行！
否则在

`ADD target/${JAR_FILE} /app.jar` 时找不到文件。导致异常：

`
Removing intermediate container 0fdba48a763d
 ---> 410ea245d61e
Step 5/6 : ADD target/${JAR_FILE} /app.jar
Error response from daemon: ADD failed: stat /var/lib/docker/tmp/docker-builder942850599/target: no such file or directory
Failed to deploy '<unknown> Dockerfile: src/main/docker/Dockerfile': Can't retrieve image ID from build stream
`

**Comment by javastacks** [comment]
可以自定义位置的
