### ISSUE TITLE
Spring Boot  2.4 及更高版本时，ApplicationEnvironmentPreparedEvent事件中修改Profile是不会生效的

### ISSUE THREAD

**Issue by Lixuhuilll** [javastacks/spring-boot-best-practice#7]
这是Spring Boot项目中的issues：https://github.com/spring-projects/spring-boot/issues/27946
这是导致该事件失效的提交：https://github.com/spring-projects/spring-boot/commit/3352024b1ca641fa0beaaa4cd87788c190242eb0

我在学习事件监听器一章时，试图在启动时根据Environment中的环境变量切换不同的Profile，但一直不生效，后来在Spring Boot官方的Issues中查找后才发现，该启动事件无法修改Profile。发在这里希望和这本书的读者一起分享一下，感觉Spring Boot框架里还是有很多坑的，光看书还是不够

**Comment by javastacks** [comment]
感谢分享，不过书中并没有说可以脖环境变量切换 profile 哦。
